package:
  name: fatools
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/nebiolabs/fatools.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - pandas
    - attrs
    
  run:
    - python

about:
  home: https://github.com/nebiolabs/fatools.git