package:
  name: fatools
  version: "0.2"

source:
  git_rev: v0.2
  git_url: https://github.com/nebiolabs/fatools.git

requirements:
  build:
    - python
    - setuptools
    - attrs
    
  run:
    - python
    - attrs
    
about:
  home: https://github.com/nebiolabs/fatools.git
