package:
  name: fatools
  version: "0.12"

source:
  git_rev: v0.12
  git_url: https://github.com/nebiolabs/fatools.git

requirements:
  build:
    - python
    - setuptools
    - attrs
    - pandas
    
  run:
    - python
    - attrs
    - pandas
    
about:
  home: https://github.com/nebiolabs/fatools.git
